---
- name: Install core command line utilities
  become: true
  package:
    name:
      - git
      - htop
      - iotop
      - vim
      - neovim
      - tmux
      - wget
      - curl
      - unzip
      - zip
      - bzip2
      - gzip
      - tar
      - rsync
      - python3
      - python3-pip
      - zsh
    state: present


- name: Install the tmux configuration file
  copy:
    src: .tmux.conf
    dest: /home/gianluca/.tmux.conf