---
- name: Install core command line utilities
  become: true
  package:
    name:
      - htop
      - iotop
      - wget
      - curl
      - unzip
      - zip
      - bzip2
      - gzip
      - tar
      - rsync
      - python
      - python-pip
      - tree
      - fzf
      - rclone
    state: present



- name: Install yay for Arch
  become: true
  package:
    name: yay
    state: present
  when: ansible_os_family == "Archlinux"

