---
- name: Install core command line utilities
  become: true
  package:
    name:
      - htop
      - iotop
      - wget
      - curl
      - unzip
      - zip
      - bzip2
      - gzip
      - tar
      - rsync
      - python3
      - python3-pip
    state: present


