---
- name: Copy alias file
  copy:
    src: .aliases
    dest: /home/gianluca/.aliases
  tags: bash

- name: Install and configure zsh using oh-my-zsh
  import_tasks: zsh.yml

- name: Setup user bin folders and path
  import_tasks: path-setup.yml

- name : Install core command line utilities
  import_tasks: core-utilities.yml

- name: Install fancy command line utilities
  import_tasks: fancy-utilities.yml

- name: Configure git
  import_tasks: git.yml

- name: Install and configure vim
  import_tasks: vim.yml

- name: Install and configure tmux
  import_tasks: tmux.yml









