- name: Install tmux
  become: true
  package:
    name: tmux
    state: latest
  tags: tmux

- name: Install tpm - tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm 
    dest: /home/gianluca/.tmux/plugins/tpm

- name: Install the tmux configuration file
  copy:
    src: .tmux.conf
    dest: /home/gianluca/.tmux.conf
  tags: tmux
