- name: Check if gvim is installed
  package_facts:
    manager: auto

- name: Install vim if gvim not installed
  become: true
  package:
    name: 
      - vim
    state: latest
  when: "'gvim' not in ansible_facts.packages"
  tags: vim

- name: Install neovim
  become: true
  package:
    name: 
      - neovim
    state: latest
  tags: vim

- name: Install ctags package
  become: true
  package:
    name: ctags
    state: present
  tags: vim

- name: Install vim configuration
  copy:
    src: .vimrc
    dest: /home/gianluca/.vimrc
  tags: vim

- name: Install Vundle - vim plugin manager
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git 
    dest: /home/gianluca/.vim/bundle/Vundle.vim
  tags: vim

- name: Install vim plugins
  command: vim -E -s -c "source /home/gianluca/.vimrc" -c PluginInstall -c qa
  tags: vim
