- name: Install zsh
  package:
    name: zsh
    state: latest
  tags: zsh

- name: Configure zsh using oh-my-zsh
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: gianluca
        oh_my_zsh:
          theme: gnzh
          plugins:
            - git
            - vi-mode
            - history-substring-search
            - zsh-autosuggestions
            - fasd
            - fzf
  tags: zsh

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/gianluca/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags: zsh

- name: Install the configuration file
  copy:
    src: .zshrc
    dest: /home/gianluca/.zshrc
  tags: zsh